"""
GC self-supervised pretraining for the EMIT-based oncology model.

This module trains the continuous-time model on the patient-excluded
General Cancer (GC) cohort. The resulting checkpoint is used to initialize
fold-specific downstream fine-tuning for Aplasia (AP) and Neutropenic Fever (NF).


Supported configurations
-------------------------
- Hybrid reconstruction--forecasting pretraining and Pure MAE pretraining.
- Target-Mask alignment modes for time, value, and variable identity.
- Standard, inverse-frequency, proportional-frequency, absolute-temporal,
  relative-temporal, and clinical-regularized reconstruction losses.
- Event-position masks generated by rate-of-change, fully random, clinical,
  frequency-adaptive, or temporal-adaptive masking.

All tensors, masks, checkpoints, and outputs are derived from restricted MIMIC-IV data and cannot be committed to a public repository.
"""

from __future__ import annotations

import json
import os
import pickle
import random
from pathlib import Path
from typing import Any

import hydra
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
from omegaconf import DictConfig, OmegaConf

from src.model import build_strats


TARGET_MODE_COMPONENTS: dict[str, tuple[tuple[int, ...], tuple[str, ...]]] = {
    "val_var_time": ((0, 1, 2), ("time", "value", "variable")),
    "val_var": ((1, 2), ("value", "variable")),
    "var_time": ((0, 2), ("time", "variable")),
    "val_time": ((0, 1), ("time", "value")),
    "val": ((1,), ("value",)),
    "var": ((2,), ("variable",)),
    "time": ((0,), ("time",)),
}

FREQUENCY_LOSSES = {"inverse_frequency", "proportional_frequency"}
VALID_LOSS_TYPES = {
    "standard",
    "inverse_frequency",
    "proportional_frequency",
    "temporal_weighted",
    "relative_temporal",
    "clinical_regularized",
}


def set_global_determinism(seed: int) -> None:
    """
    Set Python, NumPy, and TensorFlow random seeds.

    Shell scripts should additionally set PYTHONHASHSEED,
    TF_DETERMINISTIC_OPS, and TF_CUDNN_DETERMINISTIC before TensorFlow starts.
    """
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

    try:
        tf.config.experimental.enable_op_determinism()
    except AttributeError:
        pass


def validate_path(path: Path, description: str) -> None:
    """Raise a clear error when a required restricted input file is absent."""
    if not path.exists():
        raise FileNotFoundError(f"{description} not found: {path}")


def load_pretraining_arrays(
    data_path: Path,
    mask_path: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Load GC train/validation tensors, forecasting targets, and event masks.

    Returns
    -------
    train_inputs:
        Array with shape [4, n_train, max_len] for time, value, variable ID, and clinical weights.
    train_targets:
        Forecasting targets with shape [n_train, 2 * V].
    valid_inputs:
        Validation input array with the same first dimension as train_inputs.
    valid_targets:
        Validation forecasting targets.
    train_masks:
        Boolean event-position masks with shape [n_train, max_len].
    valid_masks:
        Boolean event-position masks with shape [n_valid, max_len].
    """
    validate_path(data_path, "GC pretraining tensor file")
    validate_path(mask_path, "GC event-mask file")

    with np.load(data_path, allow_pickle=False) as tensor_file:
        train_inputs = tensor_file["fore_train_ip"]
        train_targets = tensor_file["fore_train_op"]
        valid_inputs = tensor_file["fore_valid_ip"]
        valid_targets = tensor_file["fore_valid_op"]

    with np.load(mask_path, allow_pickle=False) as mask_file:
        train_masks = mask_file["fore_train_masks"]
        valid_masks = mask_file["fore_val_masks"]

    if train_inputs.shape[0] != 4 or valid_inputs.shape[0] != 4:
        raise ValueError(
            "Expected four input matrices: time, value, variable ID, and "
            "clinical weight."
        )

    if train_inputs.shape[1] != train_masks.shape[0]:
        raise ValueError("Training tensor and training-mask admission counts differ.")

    if valid_inputs.shape[1] != valid_masks.shape[0]:
        raise ValueError("Validation tensor and validation-mask admission counts differ.")

    return (
        train_inputs,
        train_targets,
        valid_inputs,
        valid_targets,
        train_masks,
        valid_masks,
    )


def target_embedding_and_choices(
    target_mode: str,
    time_embeddings: tf.Tensor,
    value_embeddings: tf.Tensor,
    variable_embeddings: tf.Tensor,
) -> tuple[tf.Tensor, tuple[int, ...]]:
    """
    Build the unmasked reconstruction target and eligible masking components.

    Components:
        0 = time
        1 = value
        2 = variable identity

    Components excluded from the target remain available as encoder context but
    are not selected for masking in that target mode.
    """
    if target_mode not in TARGET_MODE_COMPONENTS:
        valid_modes = ", ".join(TARGET_MODE_COMPONENTS)
        raise ValueError(
            f"Unsupported target_mode '{target_mode}'. Choose one of: {valid_modes}."
        )

    choices, component_names = TARGET_MODE_COMPONENTS[target_mode]
    embeddings = {
        "time": time_embeddings,
        "value": value_embeddings,
        "variable": variable_embeddings,
    }

    target = tf.add_n([embeddings[name] for name in component_names])
    return target, choices


def apply_component_mask_tokens(
    time_embeddings: tf.Tensor,
    value_embeddings: tf.Tensor,
    variable_embeddings: tf.Tensor,
    event_mask_2d: tf.Tensor,
    time_mask_token: tf.Variable,
    value_mask_token: tf.Variable,
    variable_mask_token: tf.Variable,
    allowed_choices: tuple[int, ...],
) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    """
    Replace one eligible embedding component at each selected event position.

    Every event selected by the event-position mask receives exactly one mask
    token. The component is sampled uniformly from the target-mode-specific
    eligible choices.
    """
    event_mask_2d = tf.cast(event_mask_2d, tf.bool)
    event_mask_3d = tf.expand_dims(event_mask_2d, axis=-1)

    time_token = tf.reshape(time_mask_token, [1, 1, -1])
    value_token = tf.reshape(value_mask_token, [1, 1, -1])
    variable_token = tf.reshape(variable_mask_token, [1, 1, -1])

    choice_values = tf.constant(allowed_choices, dtype=tf.int32)
    sampled_indices = tf.random.uniform(
        shape=tf.shape(event_mask_2d),
        minval=0,
        maxval=len(allowed_choices),
        dtype=tf.int32,
    )
    sampled_choices = tf.gather(choice_values, sampled_indices)

    mask_time = tf.expand_dims(tf.equal(sampled_choices, 0), axis=-1) & event_mask_3d
    mask_value = tf.expand_dims(tf.equal(sampled_choices, 1), axis=-1) & event_mask_3d
    mask_variable = (
        tf.expand_dims(tf.equal(sampled_choices, 2), axis=-1) & event_mask_3d
    )

    masked_time = tf.where(mask_time, time_token, time_embeddings)
    masked_value = tf.where(mask_value, value_token, value_embeddings)
    masked_variable = tf.where(
        mask_variable,
        variable_token,
        variable_embeddings,
    )

    return masked_time, masked_value, masked_variable


def forecast_loss(
    targets: tf.Tensor,
    predictions: tf.Tensor,
    vocabulary_size: int,
) -> tf.Tensor:
    """
    Compute forecasting loss.

    Targets contain [future values, observation indicators]. Pure MAE uses
    zero-filled targets, causing this loss to evaluate to zero.
    """
    targets = tf.cast(targets, predictions.dtype)
    future_values = targets[:, :vocabulary_size]
    observed_mask = targets[:, vocabulary_size:]

    return tf.reduce_sum(
        observed_mask * tf.square(future_values - predictions),
        axis=-1,
    )


def load_frequency_weights(
    cfg: DictConfig,
    vocabulary_size: int,
) -> tf.Tensor | None:
    """
    Load and normalize configured frequency weights.

    Frequency files reproduce the implementation and may be derived from
    full AP/NF cohort packages. Missing files raise an error rather than
    silently falling back to standard loss.
    """
    if cfg.loss_type not in FREQUENCY_LOSSES:
        return None

    if cfg.loss_type == "inverse_frequency":
        configured_path = cfg.get("inverse_frequency_weights_path")
    else:
        configured_path = cfg.get("proportional_frequency_weights_path")

    if not configured_path:
        raise ValueError(
            f"{cfg.loss_type} requires a configured frequency-weight file path."
        )

    weight_path = Path(hydra.utils.to_absolute_path(configured_path))
    validate_path(weight_path, f"{cfg.loss_type} weight file")

    with weight_path.open("rb") as handle:
        stored_weights: dict[int, float] = pickle.load(handle)

    weight_map = np.zeros(vocabulary_size + 1, dtype=np.float32)
    for variable_id, weight in stored_weights.items():
        if 0 < int(variable_id) <= vocabulary_size:
            weight_map[int(variable_id)] = float(weight)

    nonzero_weights = weight_map[weight_map > 0]
    if nonzero_weights.size == 0:
        raise ValueError(f"No non-zero weights were loaded from: {weight_path}")

    # Mean-normalization gives a mean non-zero residual multiplier of one.
    weight_map /= np.mean(nonzero_weights)
    return tf.constant(weight_map, dtype=tf.float32)


def relative_temporal_weights(
    times: tf.Tensor,
    variable_ids: tf.Tensor,
    minimum_weight: float = 0.2,
) -> tf.Tensor:
    """
    Compute relative time temporal weights per admission.

    Padding and static hour-zero demographic records are excluded when
    determining the earliest positive-time event. Admissions without a
    positive-time event use a safe fallback range.
    """
    times = tf.cast(times, tf.float32)
    valid_positive_time = (variable_ids > 0) & (times > 0.0)

    masked_min_times = tf.where(
        valid_positive_time,
        times,
        tf.constant(np.inf, dtype=tf.float32),
    )
    min_times = tf.reduce_min(masked_min_times, axis=1, keepdims=True)
    max_times = tf.reduce_max(times, axis=1, keepdims=True)

    no_positive_time = tf.math.is_inf(min_times)
    min_times = tf.where(no_positive_time, tf.zeros_like(min_times), min_times)
    max_times = tf.where(no_positive_time, tf.ones_like(max_times), max_times)

    time_ranges = tf.maximum(max_times - min_times, tf.constant(1e-5))
    scaled_time = tf.clip_by_value((times - min_times) / time_ranges, 0.0, 1.0)

    return minimum_weight + (1.0 - minimum_weight) * scaled_time


def apply_residual_weighting(
    residual: tf.Tensor,
    times: tf.Tensor,
    variable_ids: tf.Tensor,
    loss_type: str,
    frequency_weights: tf.Tensor | None,
) -> tf.Tensor:
    """
    Apply frequency or temporal weights to a residual before squaring.

    Clinical Regularization is intentionally excluded here because it multiplies
    the squared residual after masking.
    """
    if loss_type in FREQUENCY_LOSSES:
        if frequency_weights is None:
            raise RuntimeError("Frequency loss selected without frequency weights.")

        event_weights = tf.gather(frequency_weights, tf.cast(variable_ids, tf.int32))
        return residual * tf.expand_dims(event_weights, axis=-1)

    if loss_type == "temporal_weighted":
        scaled_time = tf.clip_by_value(
            tf.cast(times, tf.float32) / 336.0,
            0.0,
            1.0,
        )
        temporal_weights = 0.2 + (1.0 - 0.2) * scaled_time
        return residual * tf.expand_dims(temporal_weights, axis=-1)

    if loss_type == "relative_temporal":
        temporal_weights = relative_temporal_weights(times, variable_ids)
        return residual * tf.expand_dims(temporal_weights, axis=-1)

    return residual


def safe_mean(values: tf.Tensor) -> tf.Tensor:
    """Return zero for empty tensors and mean otherwise."""
    return tf.cond(
        tf.size(values) > 0,
        lambda: tf.reduce_mean(values),
        lambda: tf.constant(0.0, dtype=values.dtype),
    )


def reconstruction_loss(
    predictions: tf.Tensor,
    targets: tf.Tensor,
    event_mask_2d: tf.Tensor,
    clinical_weights: tf.Tensor,
    times: tf.Tensor,
    variable_ids: tf.Tensor,
    loss_type: str,
    frequency_weights: tf.Tensor | None,
) -> tf.Tensor:
    """
    Compute the configured masked latent reconstruction loss.

    Frequency and temporal variants scale the residual before squaring.
    Clinical regularization multiplies the squared residual by aligned clinical
    weights after event-mask selection.
    """
    residual = predictions - targets

    residual = apply_residual_weighting(
        residual=residual,
        times=times,
        variable_ids=variable_ids,
        loss_type=loss_type,
        frequency_weights=frequency_weights,
    )

    event_mask_2d = tf.cast(event_mask_2d, tf.bool)

    # Select complete d-dimensional residual vectors for masked events.
    # Result shape: [number_of_masked_events, d].
    masked_residual = tf.boolean_mask(residual, event_mask_2d)

    squared_error = tf.square(masked_residual)

    if loss_type == "clinical_regularized":
        # Select one scalar clinical weight per masked event, then broadcast it
        # over the embedding dimension.
        masked_clinical_weights = tf.boolean_mask(
            clinical_weights,
            event_mask_2d,
        )
        squared_error *= tf.expand_dims(masked_clinical_weights, axis=-1)

    return safe_mean(squared_error)


def forward_pretraining_pass(
    model: tf.keras.Model,
    times: tf.Tensor,
    values: tf.Tensor,
    variable_ids: tf.Tensor,
    clinical_weights: tf.Tensor,
    event_mask_2d: tf.Tensor,
    forecast_targets: tf.Tensor,
    target_mode: str,
    loss_type: str,
    frequency_weights: tf.Tensor | None,
    error_coefficient: float,
    time_mask_token: tf.Variable,
    value_mask_token: tf.Variable,
    variable_mask_token: tf.Variable,
    training: bool,
) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    """
    Run one GC pretraining forward pass and return total, reconstruction, and forecast loss.
    """
    variable_embedding = model.get_layer("variable_embedding")
    value_cve = model.get_layer("value_cve")
    time_cve = model.get_layer("time_cve")
    event_padding_mask = model.get_layer("event_padding_mask")
    transformer_encoder = model.get_layer("transformer_encoder")
    global_attention = model.get_layer("global_attention")
    attention_pooling = model.get_layer("attention_pooling")
    forecast_head = model.get_layer("forecast_head")

    variable_embeddings = variable_embedding(variable_ids)
    value_embeddings = value_cve(values)
    time_embeddings = time_cve(times)

    target_embeddings, allowed_choices = target_embedding_and_choices(
        target_mode=target_mode,
        time_embeddings=time_embeddings,
        value_embeddings=value_embeddings,
        variable_embeddings=variable_embeddings,
    )

    masked_time, masked_value, masked_variable = apply_component_mask_tokens(
        time_embeddings=time_embeddings,
        value_embeddings=value_embeddings,
        variable_embeddings=variable_embeddings,
        event_mask_2d=event_mask_2d,
        time_mask_token=time_mask_token,
        value_mask_token=value_mask_token,
        variable_mask_token=variable_mask_token,
        allowed_choices=allowed_choices,
    )

    masked_embeddings = masked_time + masked_value + masked_variable
    padding_mask = tf.cast(event_padding_mask(variable_ids), tf.float32)

    contextual_embeddings = transformer_encoder(
        masked_embeddings,
        mask=padding_mask,
        training=training,
    )

    recon_loss = reconstruction_loss(
        predictions=contextual_embeddings,
        targets=target_embeddings,
        event_mask_2d=event_mask_2d,
        clinical_weights=clinical_weights,
        times=times,
        variable_ids=variable_ids,
        loss_type=loss_type,
        frequency_weights=frequency_weights,
    )

    attention_weights = global_attention(contextual_embeddings, mask=padding_mask)
    admission_embeddings = attention_pooling(
        [contextual_embeddings, attention_weights]
    )
    forecast_predictions = forecast_head(admission_embeddings)
    forecasting = safe_mean(
        forecast_loss(
            targets=forecast_targets,
            predictions=forecast_predictions,
            vocabulary_size=int(forecast_predictions.shape[-1]),
        )
    )

    total = forecasting + error_coefficient * recon_loss
    return total, recon_loss, forecasting


def sample_epoch_indices(
    admission_count: int,
    samples_per_epoch: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Sample unique GC training admissions for one pretraining epoch."""
    if samples_per_epoch <= 0:
        raise ValueError("samples_per_epoch must be positive.")

    if samples_per_epoch > admission_count:
        raise ValueError(
            f"samples_per_epoch={samples_per_epoch} exceeds available GC "
            f"training admissions={admission_count}."
        )

    return rng.choice(
        admission_count,
        size=samples_per_epoch,
        replace=False,
    )


def save_training_metadata(
    output_path: Path,
    cfg: DictConfig,
    best_validation_loss: float,
) -> None:
    """Save non-sensitive configuration and best-loss metadata beside checkpoint."""
    metadata_path = output_path.with_suffix(".metadata.json")
    metadata = OmegaConf.to_container(cfg, resolve=True)
    metadata["best_validation_loss"] = float(best_validation_loss)

    with metadata_path.open("w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2, default=str)


@hydra.main(config_path="../../config", config_name=None, version_base=None)
def main(cfg: DictConfig) -> None:
    """Train and save the best GC self-supervised pretraining checkpoint."""
    if cfg.cohort_name != "GC":
        raise ValueError(
            "The final thesis pretraining pipeline supports GC only. "
            f"Received cohort_name={cfg.cohort_name!r}."
        )

    if cfg.loss_type not in VALID_LOSS_TYPES:
        valid_losses = ", ".join(sorted(VALID_LOSS_TYPES))
        raise ValueError(
            f"Unsupported loss_type '{cfg.loss_type}'. Choose one of: {valid_losses}."
        )

    seed = int(cfg.get("seed", 2021))
    set_global_determinism(seed)
    rng = np.random.default_rng(seed)

    data_path = Path(hydra.utils.to_absolute_path(cfg.data_path))
    mask_path = Path(hydra.utils.to_absolute_path(cfg.mask_path))
    model_base_path = Path(hydra.utils.to_absolute_path(cfg.model_name))
    model_path = model_base_path.with_suffix(".weights.h5")
    model_path.parent.mkdir(parents=True, exist_ok=True)

    (
        train_inputs,
        train_targets,
        valid_inputs,
        valid_targets,
        train_masks,
        valid_masks,
    ) = load_pretraining_arrays(data_path, mask_path)

    max_len = int(cfg.max_len)
    vocabulary_size = int(cfg.V)
    embedding_dim = int(cfg.d)

    if train_inputs.shape[2] != max_len:
        raise ValueError(
            f"Tensor max_len={train_inputs.shape[2]} does not match config max_len={max_len}."
        )

    if train_targets.shape[1] != 2 * vocabulary_size:
        raise ValueError(
            "Forecast target width does not match 2 * V. "
            f"Found {train_targets.shape[1]}, expected {2 * vocabulary_size}."
        )

    frequency_weights = load_frequency_weights(cfg, vocabulary_size)

    model = build_strats(
        max_len=max_len,
        V=vocabulary_size,
        d=embedding_dim,
        N=int(cfg.N),
        he=int(cfg.he),
        dropout=float(cfg.dropout),
    )

    learning_rate_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
        initial_learning_rate=float(cfg.learning_rate),
        decay_steps=100_000,
        decay_rate=0.96,
        staircase=True,
    )
    optimizer = tf.keras.optimizers.Adam(
        learning_rate=learning_rate_schedule,
        weight_decay=float(cfg.weight_decay),
    )

    initializer = tf.keras.initializers.GlorotUniform(seed=seed)
    time_mask_token = tf.Variable(
        initializer(shape=(1, embedding_dim)),
        trainable=True,
        name="time_mask_token",
    )
    value_mask_token = tf.Variable(
        initializer(shape=(1, embedding_dim)),
        trainable=True,
        name="value_mask_token",
    )
    variable_mask_token = tf.Variable(
        initializer(shape=(1, embedding_dim)),
        trainable=True,
        name="variable_mask_token",
    )

    trainable_variables = model.trainable_variables + [
        time_mask_token,
        value_mask_token,
        variable_mask_token,
    ]

    batch_size = int(cfg.batch_size)
    samples_per_epoch = int(cfg.samples_per_epoch)
    patience = int(cfg.patience)
    epochs = int(cfg.epochs)
    error_coefficient = float(cfg.error_coefficient)

    best_validation_loss = float("inf")
    patience_counter = 0

    print("Starting GC self-supervised pretraining.")
    print(f"Mode: {'Hybrid' if cfg.USE_FORECASTING_ABLATION else 'Pure MAE'}")
    print(f"Target mode: {cfg.target_mode}")
    print(f"Loss type: {cfg.loss_type}")
    print(f"Masking strategy: {cfg.masking_strategy}")
    print(f"GC train admissions: {train_inputs.shape[1]:,}")
    print(f"GC validation admissions: {valid_inputs.shape[1]:,}")
    print(f"Admission sequences sampled per epoch: {samples_per_epoch:,}")

    valid_dataset = tf.data.Dataset.from_tensor_slices(
        (
            valid_inputs[0],
            valid_inputs[1],
            valid_inputs[2],
            valid_inputs[3],
            valid_targets,
            valid_masks,
        )
    ).batch(batch_size).prefetch(tf.data.AUTOTUNE)

    for epoch in range(1, epochs + 1):
        epoch_indices = sample_epoch_indices(
            admission_count=train_inputs.shape[1],
            samples_per_epoch=samples_per_epoch,
            rng=rng,
        )

        train_losses: list[float] = []
        train_reconstruction_losses: list[float] = []
        train_forecasting_losses: list[float] = []

        for start in range(0, len(epoch_indices), batch_size):
            batch_indices = epoch_indices[start : start + batch_size]

            times = tf.convert_to_tensor(
                train_inputs[0, batch_indices],
                dtype=tf.float32,
            )
            values = tf.convert_to_tensor(
                train_inputs[1, batch_indices],
                dtype=tf.float32,
            )
            variable_ids = tf.convert_to_tensor(
                train_inputs[2, batch_indices],
                dtype=tf.int32,
            )
            clinical_weights = tf.convert_to_tensor(
                train_inputs[3, batch_indices],
                dtype=tf.float32,
            )
            event_mask = tf.convert_to_tensor(
                train_masks[batch_indices],
                dtype=tf.bool,
            )
            forecast_targets = tf.convert_to_tensor(
                train_targets[batch_indices],
                dtype=tf.float32,
            )

            with tf.GradientTape() as tape:
                total_loss, recon_loss, forecasting_loss = forward_pretraining_pass(
                    model=model,
                    times=times,
                    values=values,
                    variable_ids=variable_ids,
                    clinical_weights=clinical_weights,
                    event_mask_2d=event_mask,
                    forecast_targets=forecast_targets,
                    target_mode=str(cfg.target_mode),
                    loss_type=str(cfg.loss_type),
                    frequency_weights=frequency_weights,
                    error_coefficient=error_coefficient,
                    time_mask_token=time_mask_token,
                    value_mask_token=value_mask_token,
                    variable_mask_token=variable_mask_token,
                    training=True,
                )

            gradients = tape.gradient(total_loss, trainable_variables)
            gradient_variable_pairs = [
                (gradient, variable)
                for gradient, variable in zip(gradients, trainable_variables)
                if gradient is not None
            ]
            optimizer.apply_gradients(gradient_variable_pairs)

            train_losses.append(float(total_loss.numpy()))
            train_reconstruction_losses.append(float(recon_loss.numpy()))
            train_forecasting_losses.append(float(forecasting_loss.numpy()))

        validation_losses: list[float] = []
        validation_reconstruction_losses: list[float] = []
        validation_forecasting_losses: list[float] = []

        for batch in valid_dataset:
            (
                times,
                values,
                variable_ids,
                clinical_weights,
                forecast_targets,
                event_mask,
            ) = batch

            total_loss, recon_loss, forecasting_loss = forward_pretraining_pass(
                model=model,
                times=tf.cast(times, tf.float32),
                values=tf.cast(values, tf.float32),
                variable_ids=tf.cast(variable_ids, tf.int32),
                clinical_weights=tf.cast(clinical_weights, tf.float32),
                event_mask_2d=tf.cast(event_mask, tf.bool),
                forecast_targets=tf.cast(forecast_targets, tf.float32),
                target_mode=str(cfg.target_mode),
                loss_type=str(cfg.loss_type),
                frequency_weights=frequency_weights,
                error_coefficient=error_coefficient,
                time_mask_token=time_mask_token,
                value_mask_token=value_mask_token,
                variable_mask_token=variable_mask_token,
                training=False,
            )

            validation_losses.append(float(total_loss.numpy()))
            validation_reconstruction_losses.append(float(recon_loss.numpy()))
            validation_forecasting_losses.append(float(forecasting_loss.numpy()))

        mean_train_loss = float(np.mean(train_losses))
        mean_validation_loss = float(np.mean(validation_losses))
        mean_train_recon = float(np.mean(train_reconstruction_losses))
        mean_validation_recon = float(np.mean(validation_reconstruction_losses))
        mean_train_forecast = float(np.mean(train_forecasting_losses))
        mean_validation_forecast = float(np.mean(validation_forecasting_losses))

        print(
            f"Epoch {epoch:03d}/{epochs} | "
            f"train={mean_train_loss:.6f} "
            f"(recon={mean_train_recon:.6f}, forecast={mean_train_forecast:.6f}) | "
            f"valid={mean_validation_loss:.6f} "
            f"(recon={mean_validation_recon:.6f}, forecast={mean_validation_forecast:.6f})"
        )

        if mean_validation_loss < best_validation_loss:
            best_validation_loss = mean_validation_loss
            patience_counter = 0
            model.save_weights(model_path)
            save_training_metadata(
                output_path=model_path,
                cfg=cfg,
                best_validation_loss=best_validation_loss,
            )
            print(f"Saved best GC checkpoint: {model_path}")
        else:
            patience_counter += 1

        if patience_counter >= patience:
            print(
                f"Early stopping after epoch {epoch}; no validation-loss "
                f"improvement for {patience} consecutive epochs."
            )
            break

    print(f"GC pretraining completed. Best validation loss: {best_validation_loss:.6f}")


if __name__ == "__main__":
    main()